apiVersion: batch/v1
kind: CronJob
metadata:
  name: xcontest2db
spec:
  schedule: "*/19 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 900
      ttlSecondsAfterFinished: 3600
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: xcontest2db
              image: emilburzo/xcontest2db:SHORT_SHA
              imagePullPolicy: IfNotPresent
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: xcontest2db.db
                      key: host
                      optional: false
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: xcontest2db.db
                      key: username
                      optional: false
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: xcontest2db.db
                      key: password
                      optional: false